language: python
python:
    - "2.7"

sudo: false

notifications:
  email:
    on_success: never
    on_failure: change
    
cache:
    directories:
        - "~/.platformio"

env:
    - BOARD=esp01 PLATFORMIO_CI_SRC=examples/SimpleLoggingESP8266 EXTRAS="--project-option=lib_ignore=WiFi101"
    - BOARD=nodemcuv2 PLATFORMIO_CI_SRC=examples/SimpleLoggingESP8266 EXTRAS="--project-option=lib_ignore=WiFi101"

install:
    - pip install -U platformio
    - rm -rf ./linux

    #
    # Libraries from PlatformIO Library Registry:
    #
    # http://platformio.org/lib/show/299/WiFi101

    - platformio lib -g install 299

script:
    - platformio ci -v --lib="." --board=$BOARD $EXTRAS
